//! Private Node-API boundary.
//!
//! The public package facade selects and documents the reviewed surface of these
//! low-level functions. Keep this module private so it cannot be confused with
//! the broader Rust-only `pi_tui` compatibility namespace.

// The Node-API registration generated by `#[napi]` is the consumer. Rust's
// lib-test harness disables that registration and otherwise reports every ABI
// entry point as unused.
#![cfg_attr(test, allow(dead_code))]

use napi::bindgen_prelude::{Either, Null, Utf16String};
use napi::{Error, Result, Status};
use napi_derive::napi;
use pie_components::{
    Component, DetachedEditorHost, Editor, EditorOptions, EditorTheme, Input, Loader,
    LoaderIndicatorOptions, Markdown, MarkdownOptions, MarkdownTheme, Spacer, StackEntry, Text,
    TruncatedText, allocate_stack_sizes,
};
use pie_core::frame::LogicalFrame;
use pie_core::keybindings::KeybindingShape;
use pie_core::latex::RenderLatexOptions;
use pie_core::stdin_buffer::{StdinBuffer as CoreStdinBuffer, StdinEvent};
use pie_core::terminal_colors::TerminalColorScheme;
use pie_core::terminal_image::{
    CellDimensions, ITerm2Dimension, ITerm2EncodeOptions, ImageDimensions, KittyEncodeOptions,
};
use pie_core::text::{extract_ansi_code_len, grapheme_width};
use pie_core::wrap::AnsiCodeTracker;
use pie_term::capabilities::TerminalEnvironment;
use pie_term::renderer::{MainScreenRenderer, RenderState};
use pie_term::{InputHandler, ResizeHandler, Terminal};
use unicode_segmentation::UnicodeSegmentation;

const KITTY_UTF16_CHUNK_SIZE: usize = 4096;

#[napi(object)]
pub struct NativeMainScreenRenderState {
    pub previous_lines: Vec<String>,
    pub previous_width: i32,
    pub previous_height: i32,
    pub cursor_row: i32,
    pub hardware_cursor_row: i32,
    pub max_lines_rendered: u32,
    pub previous_viewport_top: u32,
}

impl From<RenderState> for NativeMainScreenRenderState {
    fn from(state: RenderState) -> Self {
        Self {
            previous_lines: state.previous_lines,
            previous_width: state
                .previous_width
                .clamp(i32::MIN as isize, i32::MAX as isize) as i32,
            previous_height: state
                .previous_height
                .clamp(i32::MIN as isize, i32::MAX as isize) as i32,
            cursor_row: state.cursor_row.clamp(i32::MIN as isize, i32::MAX as isize) as i32,
            hardware_cursor_row: state
                .hardware_cursor_row
                .clamp(i32::MIN as isize, i32::MAX as isize)
                as i32,
            max_lines_rendered: state.max_lines_rendered.min(u32::MAX as usize) as u32,
            previous_viewport_top: state.previous_viewport_top.min(u32::MAX as usize) as u32,
        }
    }
}

impl From<NativeMainScreenRenderState> for RenderState {
    fn from(state: NativeMainScreenRenderState) -> Self {
        Self {
            previous_lines: state.previous_lines,
            previous_width: state.previous_width as isize,
            previous_height: state.previous_height as isize,
            cursor_row: state.cursor_row as isize,
            hardware_cursor_row: state.hardware_cursor_row as isize,
            max_lines_rendered: state.max_lines_rendered as usize,
            previous_viewport_top: state.previous_viewport_top as usize,
        }
    }
}

struct NativePlanTerminal {
    actions: Vec<NativeTerminalAction>,
    columns: usize,
    rows: usize,
}

#[napi(object)]
pub struct NativeTerminalAction {
    pub kind: String,
    pub data: Option<String>,
}

impl Terminal for NativePlanTerminal {
    fn start(&mut self, _on_input: InputHandler, _on_resize: ResizeHandler) {}
    fn stop(&mut self) {}
    fn write(&mut self, data: &str) {
        self.actions.push(NativeTerminalAction {
            kind: "write".to_owned(),
            data: Some(data.to_owned()),
        });
    }
    fn columns(&self) -> usize {
        self.columns
    }
    fn rows(&self) -> usize {
        self.rows
    }
    fn kitty_protocol_active(&self) -> bool {
        false
    }
    fn move_by(&mut self, lines: isize) {
        if lines > 0 {
            self.write(&format!("\x1b[{lines}B"));
        } else if lines < 0 {
            self.write(&format!("\x1b[{}A", -lines));
        }
    }
    fn hide_cursor(&mut self) {
        self.actions.push(NativeTerminalAction {
            kind: "hideCursor".to_owned(),
            data: None,
        });
    }
    fn show_cursor(&mut self) {
        self.actions.push(NativeTerminalAction {
            kind: "showCursor".to_owned(),
            data: None,
        });
    }
    fn clear_line(&mut self) {
        self.write("\x1b[K");
    }
    fn clear_from_cursor(&mut self) {
        self.write("\x1b[J");
    }
    fn clear_screen(&mut self) {
        self.write("\x1b[2J\x1b[H");
    }
    fn set_title(&mut self, title: &str) {
        self.write(&format!("\x1b]0;{title}\x07"));
    }
    fn set_progress(&mut self, active: bool) {
        self.write(if active {
            "\x1b]9;4;3\x07"
        } else {
            "\x1b]9;4;0\x07"
        });
    }
}

#[napi]
pub struct NativeMainScreenPlanner {
    inner: MainScreenRenderer,
}

#[napi]
pub struct NativeAltScreenPlanner {
    previous_screen: Vec<String>,
    previous_width: u32,
    previous_height: u32,
    full_redraws: u32,
}

#[napi]
impl NativeAltScreenPlanner {
    #[napi(constructor)]
    pub fn new() -> Self {
        Self {
            previous_screen: Vec::new(),
            previous_width: 0,
            previous_height: 0,
            full_redraws: 0,
        }
    }

    #[napi]
    pub fn reset(&mut self) {
        self.previous_screen.clear();
        self.previous_width = 0;
        self.previous_height = 0;
    }

    #[napi(getter)]
    pub fn full_redraws(&self) -> u32 {
        self.full_redraws
    }

    #[napi]
    pub fn render(&mut self, mut screen: Vec<String>, columns: u32, rows: u32) -> String {
        let width = columns.max(1);
        let height = rows.max(1);
        screen.truncate(height as usize);
        let full_redraw = self.previous_screen.is_empty()
            || self.previous_width != width
            || self.previous_height != height;
        let mut buffer = String::from("\x1b[?2026h");
        if full_redraw {
            self.full_redraws = self.full_redraws.saturating_add(1);
            buffer.push_str("\x1b[2J");
        }
        for row in 0..height as usize {
            let line = screen.get(row).map_or("", String::as_str);
            if !full_redraw && self.previous_screen.get(row).map_or("", String::as_str) == line {
                continue;
            }
            buffer.push_str(&format!(
                "\x1b[{};1H\x1b[2K{line}\x1b[0m\x1b]8;;\x07",
                row + 1
            ));
        }
        buffer.push_str("\x1b[?25l\x1b[?2026l");
        self.previous_screen = screen;
        self.previous_width = width;
        self.previous_height = height;
        buffer
    }
}

#[napi]
impl NativeMainScreenPlanner {
    #[napi(constructor)]
    pub fn new() -> Self {
        Self {
            inner: MainScreenRenderer::new(),
        }
    }

    #[napi]
    pub fn render(
        &mut self,
        lines: Vec<String>,
        columns: u32,
        rows: u32,
        force: bool,
        clear_on_shrink: bool,
        show_hardware_cursor: bool,
    ) -> Result<Vec<NativeTerminalAction>> {
        let width = columns.max(1) as usize;
        let height = rows.max(1) as usize;
        let frame = LogicalFrame::new(lines, width, height).map_err(|error| {
            Error::new(
                Status::InvalidArg,
                format!("invalid logical frame: {error:?}"),
            )
        })?;
        self.inner.set_clear_on_shrink(clear_on_shrink);
        self.inner.set_show_hardware_cursor(show_hardware_cursor);
        let mut terminal = NativePlanTerminal {
            actions: Vec::new(),
            columns: width,
            rows: height,
        };
        self.inner
            .render_frame(&mut terminal, &frame, force)
            .map_err(|error| {
                Error::new(
                    Status::GenericFailure,
                    format!("main-screen render failed: {error:?}"),
                )
            })?;
        Ok(terminal.actions)
    }

    #[napi]
    pub fn reset(&mut self) {
        self.inner.reset_render_state();
    }

    #[napi]
    pub fn set_stopped(&mut self, stopped: bool) {
        self.inner.set_stopped(stopped);
    }

    #[napi(getter)]
    pub fn full_redraws(&self) -> u32 {
        self.inner.full_redraws().min(u32::MAX as usize) as u32
    }

    #[napi]
    pub fn capture(&self) -> NativeMainScreenRenderState {
        self.inner.capture_render_state().into()
    }

    #[napi]
    pub fn restore(&mut self, state: NativeMainScreenRenderState) {
        self.inner.restore_render_state(state.into());
    }
}

#[napi(object)]
pub struct NativeFuzzyResult {
    pub matches: bool,
    pub score: f64,
}

#[napi(object)]
pub struct NativeKeybindingDefinition {
    pub id: String,
    pub default_keys: Either<String, Vec<String>>,
    pub description: String,
}

#[napi(object)]
pub struct NativeCompositeSegments {
    pub before: String,
    pub before_width: f64,
    pub after: String,
    pub after_width: f64,
}

#[napi(object)]
pub struct NativeStackEntry {
    pub basis: Option<u32>,
    pub grow: Option<u32>,
    pub shrink: Option<u32>,
    pub min_size: Option<u32>,
    pub max_size: Option<u32>,
}

#[napi(js_name = "nativeAllocateStackSizes")]
pub fn native_allocate_stack_sizes(
    entries: Vec<NativeStackEntry>,
    intrinsic_sizes: Vec<u32>,
    available_size: Option<u32>,
    gap: u32,
) -> Vec<u32> {
    let entries: Vec<StackEntry> = entries
        .into_iter()
        .map(|entry| StackEntry {
            basis: entry.basis.map(|value| value as usize),
            grow: entry.grow.unwrap_or(0) as usize,
            shrink: entry.shrink.unwrap_or(1) as usize,
            min_size: entry.min_size.unwrap_or(0) as usize,
            max_size: entry.max_size.map_or(usize::MAX, |value| value as usize),
            visible: None,
        })
        .collect();
    let intrinsic_sizes: Vec<usize> = intrinsic_sizes
        .into_iter()
        .map(|value| value as usize)
        .collect();
    allocate_stack_sizes(
        &entries,
        &intrinsic_sizes,
        available_size.map(|value| value as usize),
        gap as usize,
    )
    .into_iter()
    .map(|value| value.min(u32::MAX as usize) as u32)
    .collect()
}

#[napi]
pub struct NativeSpacerState {
    inner: Spacer,
}

#[napi]
pub struct NativeTextState {
    inner: Text,
}

#[napi]
impl NativeTextState {
    #[napi(constructor)]
    pub fn new(text: String, padding_x: u32, padding_y: u32) -> Self {
        Self {
            inner: Text::with_padding(text, padding_x as usize, padding_y as usize),
        }
    }

    #[napi]
    pub fn set_text(&mut self, text: String) {
        self.inner.set_text(text);
    }

    #[napi]
    pub fn invalidate(&mut self) {
        self.inner.invalidate();
    }

    #[napi]
    pub fn render(&mut self, width: u32) -> Vec<String> {
        self.inner.render(width as usize)
    }
}

#[napi]
pub struct NativeTruncatedTextState {
    inner: TruncatedText,
}

#[napi]
impl NativeTruncatedTextState {
    #[napi(constructor)]
    pub fn new(text: String, padding_x: u32, padding_y: u32) -> Self {
        Self {
            inner: TruncatedText::with_padding(text, padding_x as usize, padding_y as usize),
        }
    }

    #[napi]
    pub fn invalidate(&mut self) {
        self.inner.invalidate();
    }

    #[napi]
    pub fn render(&mut self, width: u32) -> Vec<String> {
        self.inner.render(width as usize)
    }
}

#[napi(object)]
pub struct NativeInputEvents {
    pub submit: Option<String>,
    pub escape: bool,
}

#[napi(object)]
pub struct NativeStdinEvent {
    pub kind: String,
    pub value: String,
}

fn native_stdin_events(events: Vec<StdinEvent>) -> Vec<NativeStdinEvent> {
    events
        .into_iter()
        .map(|event| match event {
            StdinEvent::Data(value) => NativeStdinEvent {
                kind: "data".to_owned(),
                value,
            },
            StdinEvent::Paste(value) => NativeStdinEvent {
                kind: "paste".to_owned(),
                value,
            },
        })
        .collect()
}

#[napi]
pub struct NativeStdinBufferState {
    inner: CoreStdinBuffer,
}

#[napi]
impl NativeStdinBufferState {
    #[napi(constructor)]
    pub fn new(timeout_ms: u32) -> Self {
        Self {
            inner: CoreStdinBuffer::new(u64::from(timeout_ms)),
        }
    }

    #[napi]
    pub fn process(&mut self, data: String) -> Vec<NativeStdinEvent> {
        native_stdin_events(self.inner.process(&data))
    }

    #[napi]
    pub fn flush(&mut self) -> Vec<String> {
        self.inner
            .flush()
            .into_iter()
            .filter_map(|event| match event {
                StdinEvent::Data(value) => Some(value),
                StdinEvent::Paste(_) => None,
            })
            .collect()
    }

    #[napi]
    pub fn clear(&mut self) {
        self.inner.clear();
    }

    #[napi]
    pub fn get_buffer(&self) -> String {
        self.inner.get_buffer().to_owned()
    }
}

#[napi]
pub struct NativeInputState {
    inner: Input,
    submitted: std::sync::Arc<std::sync::Mutex<Option<String>>>,
    escaped: std::sync::Arc<std::sync::atomic::AtomicBool>,
}

#[napi]
impl NativeInputState {
    #[napi(constructor)]
    pub fn new() -> Self {
        let submitted = std::sync::Arc::new(std::sync::Mutex::new(None));
        let escaped = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
        let mut inner = Input::new();
        let submit_slot = submitted.clone();
        inner.set_on_submit(Some(Box::new(move |value| {
            *submit_slot.lock().expect("input submit slot poisoned") = Some(value);
        })));
        let escape_slot = escaped.clone();
        inner.set_on_escape(Some(Box::new(move || {
            escape_slot.store(true, std::sync::atomic::Ordering::SeqCst);
        })));
        Self {
            inner,
            submitted,
            escaped,
        }
    }

    #[napi(getter)]
    pub fn focused(&self) -> bool {
        self.inner.focused
    }

    #[napi(setter)]
    pub fn set_focused(&mut self, focused: bool) {
        self.inner.focused = focused;
    }

    #[napi]
    pub fn get_value(&self) -> String {
        self.inner.get_value().to_owned()
    }

    #[napi]
    pub fn set_value(&mut self, value: String) {
        self.inner.set_value(value);
    }

    #[napi]
    pub fn handle_input(&mut self, data: String) -> NativeInputEvents {
        self.inner.handle_input(&data);
        NativeInputEvents {
            submit: self
                .submitted
                .lock()
                .expect("input submit slot poisoned")
                .take(),
            escape: self
                .escaped
                .swap(false, std::sync::atomic::Ordering::SeqCst),
        }
    }

    #[napi]
    pub fn invalidate(&mut self) {
        self.inner.invalidate();
    }

    #[napi]
    pub fn render(&mut self, width: u32) -> Vec<String> {
        self.inner.render(width as usize)
    }
}

impl Default for NativeInputState {
    fn default() -> Self {
        Self::new()
    }
}

#[napi]
pub struct NativeLoaderState {
    inner: Loader,
}

#[napi(object)]
pub struct NativeEditorCursor {
    pub line: u32,
    pub col: u32,
}

#[napi(object)]
pub struct NativeEditorEvents {
    pub submit: Option<String>,
    pub change: Option<String>,
}

#[napi]
pub struct NativeEditorState {
    inner: Editor,
    submitted: std::sync::Arc<std::sync::Mutex<Option<String>>>,
    changed: std::sync::Arc<std::sync::Mutex<Option<String>>>,
}

#[napi]
impl NativeEditorState {
    #[napi(constructor)]
    pub fn new(padding_x: u32, autocomplete_max_visible: Option<u32>) -> Self {
        let submitted = std::sync::Arc::new(std::sync::Mutex::new(None));
        let changed = std::sync::Arc::new(std::sync::Mutex::new(None));
        let mut inner = Editor::new(
            Box::new(DetachedEditorHost::default()),
            EditorTheme::plain(),
            EditorOptions {
                padding_x: padding_x as usize,
                autocomplete_max_visible: autocomplete_max_visible.map(|value| value as usize),
                word_segmenter: None,
            },
        );
        let submit_slot = submitted.clone();
        inner.set_on_submit(Some(Box::new(move |value| {
            *submit_slot.lock().expect("editor submit slot poisoned") = Some(value);
        })));
        let change_slot = changed.clone();
        inner.set_on_change(Some(Box::new(move |value| {
            *change_slot.lock().expect("editor change slot poisoned") = Some(value);
        })));
        Self {
            inner,
            submitted,
            changed,
        }
    }

    #[napi(getter)]
    pub fn focused(&self) -> bool {
        self.inner.focused
    }

    #[napi(setter)]
    pub fn set_focused(&mut self, focused: bool) {
        self.inner.focused = focused;
    }

    #[napi(getter)]
    pub fn disable_submit(&self) -> bool {
        self.inner.disable_submit
    }

    #[napi(setter)]
    pub fn set_disable_submit(&mut self, disable: bool) {
        self.inner.disable_submit = disable;
    }

    #[napi]
    pub fn get_padding_x(&self) -> u32 {
        self.inner.get_padding_x().min(u32::MAX as usize) as u32
    }

    #[napi]
    pub fn set_padding_x(&mut self, padding: u32) {
        self.inner.set_padding_x(padding as usize);
    }

    #[napi]
    pub fn get_autocomplete_max_visible(&self) -> u32 {
        self.inner
            .get_autocomplete_max_visible()
            .min(u32::MAX as usize) as u32
    }

    #[napi]
    pub fn set_autocomplete_max_visible(&mut self, max_visible: u32) {
        self.inner
            .set_autocomplete_max_visible(max_visible as usize);
    }

    #[napi]
    pub fn add_to_history(&mut self, text: String) {
        self.inner.add_to_history(text);
    }

    #[napi]
    pub fn get_text(&self) -> String {
        self.inner.get_text()
    }

    #[napi]
    pub fn get_expanded_text(&self) -> String {
        self.inner.get_expanded_text()
    }

    #[napi]
    pub fn get_lines(&self) -> Vec<String> {
        self.inner.get_lines()
    }

    #[napi]
    pub fn get_cursor(&self) -> NativeEditorCursor {
        let cursor = self.inner.get_cursor();
        NativeEditorCursor {
            line: cursor.line.min(u32::MAX as usize) as u32,
            col: cursor.col.min(u32::MAX as usize) as u32,
        }
    }

    #[napi]
    pub fn set_text(&mut self, text: String) -> NativeEditorEvents {
        self.inner.set_text(text);
        self.take_events()
    }

    #[napi]
    pub fn insert_text_at_cursor(&mut self, text: String) -> NativeEditorEvents {
        self.inner.insert_text_at_cursor(text);
        self.take_events()
    }

    #[napi]
    pub fn handle_input(&mut self, data: String) -> NativeEditorEvents {
        self.inner.handle_input(&data);
        self.take_events()
    }

    #[napi]
    pub fn is_showing_autocomplete(&self) -> bool {
        self.inner.is_showing_autocomplete()
    }

    #[napi]
    pub fn invalidate(&mut self) {
        self.inner.invalidate();
    }

    #[napi]
    pub fn render(&mut self, width: u32) -> Vec<String> {
        self.inner.render(width as usize)
    }
}

impl NativeEditorState {
    fn take_events(&self) -> NativeEditorEvents {
        NativeEditorEvents {
            submit: self
                .submitted
                .lock()
                .expect("editor submit slot poisoned")
                .take(),
            change: self
                .changed
                .lock()
                .expect("editor change slot poisoned")
                .take(),
        }
    }
}

fn plain_markdown_theme() -> MarkdownTheme {
    fn style() -> pie_components::StyleFn {
        Box::new(str::to_owned)
    }
    MarkdownTheme {
        heading: style(),
        link: style(),
        link_url: style(),
        code: style(),
        code_block: style(),
        code_block_border: style(),
        quote: style(),
        quote_border: style(),
        hr: style(),
        list_bullet: style(),
        bold: style(),
        italic: style(),
        strikethrough: style(),
        underline: style(),
        highlight_code: None,
        code_block_indent: None,
    }
}

#[napi]
pub struct NativeMarkdownState {
    inner: Markdown,
}

#[napi]
impl NativeMarkdownState {
    #[napi(constructor)]
    pub fn new(
        text: String,
        padding_x: u32,
        padding_y: u32,
        preserve_ordered_list_markers: Option<bool>,
        preserve_backslash_escapes: Option<bool>,
        render_latex: Option<bool>,
    ) -> Self {
        Self {
            inner: Markdown::new(
                text,
                padding_x as usize,
                padding_y as usize,
                plain_markdown_theme(),
                None,
                MarkdownOptions {
                    preserve_ordered_list_markers: preserve_ordered_list_markers.unwrap_or(false),
                    preserve_backslash_escapes: preserve_backslash_escapes.unwrap_or(false),
                    transform: None,
                    render_latex: render_latex.unwrap_or(true),
                },
            ),
        }
    }

    #[napi]
    pub fn set_text(&mut self, text: String) {
        self.inner.set_text(text);
    }

    #[napi]
    pub fn invalidate(&mut self) {
        self.inner.invalidate();
    }

    #[napi]
    pub fn render(&mut self, width: u32) -> Vec<String> {
        self.inner.render(width as usize)
    }
}

#[napi]
impl NativeLoaderState {
    #[napi(constructor)]
    pub fn new(message: String, frames: Option<Vec<String>>, interval_ms: Option<u32>) -> Self {
        let indicator = Some(LoaderIndicatorOptions {
            frames,
            interval_ms: interval_ms.map(u64::from),
        });
        Self {
            inner: Loader::with_colors(message, None, None, indicator),
        }
    }

    #[napi(getter)]
    pub fn interval_ms(&self) -> u32 {
        self.inner.interval_ms().min(u64::from(u32::MAX)) as u32
    }

    #[napi(getter)]
    pub fn running(&self) -> bool {
        self.inner.is_running()
    }

    #[napi]
    pub fn set_message(&mut self, message: String) {
        self.inner.set_message(message);
    }

    #[napi]
    pub fn set_indicator(&mut self, frames: Option<Vec<String>>, interval_ms: Option<u32>) {
        self.inner.set_indicator(Some(LoaderIndicatorOptions {
            frames,
            interval_ms: interval_ms.map(u64::from),
        }));
    }

    #[napi]
    pub fn advance_frame(&mut self) {
        self.inner.advance_frame();
    }

    #[napi]
    pub fn start(&mut self) {
        self.inner.start();
    }

    #[napi]
    pub fn stop(&mut self) {
        self.inner.stop();
    }

    #[napi]
    pub fn invalidate(&mut self) {
        self.inner.invalidate();
    }

    #[napi]
    pub fn render(&mut self, width: u32) -> Vec<String> {
        self.inner.render(width as usize)
    }
}

#[napi]
impl NativeSpacerState {
    #[napi(constructor)]
    pub fn new() -> Self {
        Self {
            inner: Spacer::new(1),
        }
    }

    #[napi]
    pub fn set_lines(&mut self, lines: f64) -> Result<()> {
        let count = if lines.is_nan() || lines <= 0.0 {
            0
        } else if !lines.is_finite() || lines.ceil() > u32::MAX as f64 {
            return Err(Error::new(
                Status::InvalidArg,
                "Spacer line count exceeds the JavaScript array limit",
            ));
        } else {
            lines.ceil() as usize
        };
        self.inner.set_lines(count);
        Ok(())
    }

    #[napi]
    pub fn render(&mut self) -> Vec<String> {
        self.inner.render(0)
    }
}

impl Default for NativeSpacerState {
    fn default() -> Self {
        Self::new()
    }
}

#[napi(object)]
pub struct NativeRenderLatexOptions {
    pub display: Option<bool>,
}

#[napi(object)]
pub struct NativeRgbColor {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

#[napi(object)]
pub struct NativeCellDimensions {
    pub width_px: f64,
    pub height_px: f64,
}

impl From<NativeCellDimensions> for CellDimensions {
    fn from(value: NativeCellDimensions) -> Self {
        Self {
            width_px: value.width_px,
            height_px: value.height_px,
        }
    }
}

#[napi(object)]
pub struct NativeImageDimensions {
    pub width_px: u32,
    pub height_px: u32,
}

impl From<NativeImageDimensions> for ImageDimensions {
    fn from(value: NativeImageDimensions) -> Self {
        Self {
            width_px: value.width_px,
            height_px: value.height_px,
        }
    }
}

impl From<ImageDimensions> for NativeImageDimensions {
    fn from(value: ImageDimensions) -> Self {
        Self {
            width_px: value.width_px,
            height_px: value.height_px,
        }
    }
}

#[napi(object)]
pub struct NativeTerminalCapabilities {
    pub images: Either<String, Null>,
    pub true_color: bool,
    pub hyperlinks: bool,
}

#[napi(object)]
pub struct NativeTerminalEnvironment {
    pub term_program: Option<String>,
    pub terminal_emulator: Option<String>,
    pub term: Option<String>,
    pub color_term: Option<String>,
    pub tmux: Option<String>,
    pub kitty_window_id: Option<String>,
    pub ghostty_resources_dir: Option<String>,
    pub wezterm_pane: Option<String>,
    pub warp_session_id: Option<String>,
    pub warp_terminal_session_uuid: Option<String>,
    pub iterm_session_id: Option<String>,
    pub wt_session: Option<String>,
}

impl NativeTerminalEnvironment {
    fn into_terminal_environment(self) -> TerminalEnvironment {
        TerminalEnvironment::from_pairs(
            cfg!(windows),
            [
                ("TERM_PROGRAM", self.term_program.as_deref().unwrap_or("")),
                (
                    "TERMINAL_EMULATOR",
                    self.terminal_emulator.as_deref().unwrap_or(""),
                ),
                ("TERM", self.term.as_deref().unwrap_or("")),
                ("COLORTERM", self.color_term.as_deref().unwrap_or("")),
                ("TMUX", self.tmux.as_deref().unwrap_or("")),
                (
                    "KITTY_WINDOW_ID",
                    self.kitty_window_id.as_deref().unwrap_or(""),
                ),
                (
                    "GHOSTTY_RESOURCES_DIR",
                    self.ghostty_resources_dir.as_deref().unwrap_or(""),
                ),
                ("WEZTERM_PANE", self.wezterm_pane.as_deref().unwrap_or("")),
                (
                    "WARP_SESSION_ID",
                    self.warp_session_id.as_deref().unwrap_or(""),
                ),
                (
                    "WARP_TERMINAL_SESSION_UUID",
                    self.warp_terminal_session_uuid.as_deref().unwrap_or(""),
                ),
                (
                    "ITERM_SESSION_ID",
                    self.iterm_session_id.as_deref().unwrap_or(""),
                ),
                ("WT_SESSION", self.wt_session.as_deref().unwrap_or("")),
            ],
        )
    }
}

#[napi(object)]
#[derive(Default)]
pub struct NativeKittyEncodeOptions {
    pub columns: Option<u32>,
    pub rows: Option<u32>,
    pub image_id: Option<u32>,
    pub move_cursor: Option<bool>,
}

#[napi(object)]
#[derive(Default)]
pub struct NativeITerm2EncodeOptions {
    pub width: Option<String>,
    pub height: Option<String>,
    pub name: Option<String>,
    pub preserve_aspect_ratio: Option<bool>,
    pub inline: Option<bool>,
}

fn push_utf16(output: &mut Vec<u16>, value: &str) {
    output.extend(value.encode_utf16());
}

fn js_is_whitespace_unit(unit: u16) -> bool {
    matches!(
        unit,
        0x0009..=0x000d
            | 0x0020
            | 0x00a0
            | 0x1680
            | 0x2000..=0x200a
            | 0x2028
            | 0x2029
            | 0x202f
            | 0x205f
            | 0x3000
            | 0xfeff
    )
}

fn fuzzy_match_query(query: &[u16], text: &[u16]) -> NativeFuzzyResult {
    if query.is_empty() {
        return NativeFuzzyResult {
            matches: true,
            score: 0.0,
        };
    }
    if query.len() > text.len() {
        return NativeFuzzyResult {
            matches: false,
            score: 0.0,
        };
    }

    let mut query_index = 0usize;
    let mut score = 0.0f64;
    let mut last_match_index = -1isize;
    let mut consecutive_matches = 0i64;
    for (index, unit) in text.iter().copied().enumerate() {
        if query_index >= query.len() {
            break;
        }
        if unit != query[query_index] {
            continue;
        }
        let is_word_boundary = index == 0
            || js_is_whitespace_unit(text[index - 1])
            || matches!(text[index - 1], 0x002d | 0x005f | 0x002e | 0x002f | 0x003a);
        if last_match_index == index as isize - 1 {
            consecutive_matches += 1;
            score -= (consecutive_matches * 5) as f64;
        } else {
            consecutive_matches = 0;
            if last_match_index >= 0 {
                score += (index as isize - last_match_index - 1) as f64 * 2.0;
            }
        }
        if is_word_boundary {
            score -= 10.0;
        }
        score += index as f64 * 0.1;
        last_match_index = index as isize;
        query_index += 1;
    }
    if query_index < query.len() {
        return NativeFuzzyResult {
            matches: false,
            score: 0.0,
        };
    }
    if query == text {
        score -= 100.0;
    }
    NativeFuzzyResult {
        matches: true,
        score,
    }
}

fn swapped_ascii_query(query: &[u16]) -> Option<Vec<u16>> {
    let is_digit = |unit: u16| (u16::from(b'0')..=u16::from(b'9')).contains(&unit);
    let is_letter = |unit: u16| (u16::from(b'a')..=u16::from(b'z')).contains(&unit);
    if !query
        .first()
        .copied()
        .is_some_and(|unit| is_digit(unit) || is_letter(unit))
    {
        return None;
    }
    let letters_then_digits = {
        let letters_end = query
            .iter()
            .position(|unit| is_digit(*unit))
            .unwrap_or(query.len());
        letters_end > 0
            && letters_end < query.len()
            && query[..letters_end].iter().all(|unit| is_letter(*unit))
            && query[letters_end..].iter().all(|unit| is_digit(*unit))
    };
    let digits_then_letters = {
        let digits_end = query
            .iter()
            .position(|unit| !is_digit(*unit))
            .unwrap_or(query.len());
        digits_end > 0
            && digits_end < query.len()
            && query[..digits_end].iter().all(|unit| is_digit(*unit))
            && query[digits_end..].iter().all(|unit| is_letter(*unit))
    };
    let split = if letters_then_digits {
        query.iter().position(|unit| is_digit(*unit))?
    } else if digits_then_letters {
        query.iter().position(|unit| !is_digit(*unit))?
    } else {
        return None;
    };
    let mut swapped = Vec::with_capacity(query.len());
    swapped.extend_from_slice(&query[split..]);
    swapped.extend_from_slice(&query[..split]);
    Some(swapped)
}

#[napi(js_name = "nativeFuzzyMatchLowerUtf16")]
pub fn native_fuzzy_match_lower_utf16(
    query_lower: Utf16String,
    text_lower: Utf16String,
) -> NativeFuzzyResult {
    let query_lower = query_lower.to_vec();
    let text_lower = text_lower.to_vec();
    let primary = fuzzy_match_query(&query_lower, &text_lower);
    if primary.matches {
        return primary;
    }
    let Some(swapped) = swapped_ascii_query(&query_lower) else {
        return primary;
    };
    let mut matched = fuzzy_match_query(&swapped, &text_lower);
    if matched.matches {
        matched.score += 5.0;
        matched
    } else {
        primary
    }
}

#[napi(js_name = "nativeGetTuiKeybindingDefinitions")]
pub fn native_get_tui_keybinding_definitions() -> Vec<NativeKeybindingDefinition> {
    pie_core::keybindings::TUI_KEYBINDINGS
        .iter()
        .map(|definition| NativeKeybindingDefinition {
            id: definition.id.to_owned(),
            default_keys: match definition.default_shape {
                KeybindingShape::Scalar => Either::A(definition.default_keys[0].to_owned()),
                KeybindingShape::List => Either::B(
                    definition
                        .default_keys
                        .iter()
                        .map(|key| (*key).to_owned())
                        .collect(),
                ),
            },
            description: definition.description.to_owned(),
        })
        .collect()
}

#[napi(js_name = "nativeCursorMarker")]
pub fn native_cursor_marker() -> String {
    pie_core::screen::CURSOR_MARKER.to_owned()
}

fn raw_utf16_token_len(line: &str, index: usize, token_prefix: &str) -> Option<usize> {
    if token_prefix.is_empty() || !line[index..].starts_with(token_prefix) {
        return None;
    }
    let payload_start = index + token_prefix.len();
    let payload_end = payload_start.checked_add(32)?;
    let terminator = payload_end.checked_add(1)?;
    let bytes = line.as_bytes();
    if terminator > bytes.len()
        || !bytes[payload_start..payload_end]
            .iter()
            .all(|byte| matches!(byte, b'\x02' | b'\x03'))
        || bytes[payload_end] != b'\x04'
    {
        return None;
    }
    Some(terminator - index)
}

fn composite_grapheme_at<'a>(
    line: &'a str,
    index: usize,
    text_end: usize,
    token_prefix: &str,
) -> (&'a str, f64) {
    if let Some(token_len) = raw_utf16_token_len(line, index, token_prefix) {
        // A lone JavaScript surrogate has Grapheme_Cluster_Break=Other. Model it
        // with a temporary scalar only for segmentation so trailing marks/ZWJ
        // stay attached; keep the collision-free encoded token in the output.
        const PROBE: char = '\u{e000}';
        let suffix = &line[index + token_len..text_end];
        let mut probe = String::with_capacity(PROBE.len_utf8() + suffix.len());
        probe.push(PROBE);
        probe.push_str(suffix);
        let probe_len = probe.graphemes(true).next().map(str::len).unwrap_or(0);
        let suffix_len = probe_len.saturating_sub(PROBE.len_utf8());
        return (&line[index..index + token_len + suffix_len], 0.0);
    }

    let segment = line[index..text_end]
        .graphemes(true)
        .next()
        .expect("index is before text_end");
    (segment, grapheme_width(segment) as f64)
}

#[napi(js_name = "nativeCompositeVisibleWidth")]
pub fn native_composite_visible_width(line: String, token_prefix: String) -> f64 {
    let mut width = 0.0;
    let mut index = 0;
    while index < line.len() {
        if let Some(length) = extract_ansi_code_len(&line, index) {
            index += length;
            continue;
        }

        let mut text_end = index;
        while text_end < line.len() && extract_ansi_code_len(&line, text_end).is_none() {
            text_end += 1;
        }
        while index < text_end {
            let (segment, segment_width) =
                composite_grapheme_at(&line, index, text_end, &token_prefix);
            width += segment_width;
            index += segment.len();
        }
    }
    width
}

#[napi(js_name = "nativeExtractCompositeSegments")]
pub fn native_extract_composite_segments(
    line: String,
    before_end: f64,
    after_start: f64,
    after_len: f64,
    token_prefix: String,
) -> NativeCompositeSegments {
    // Keep JavaScript Number boundaries fractional: zero-width graphemes can be
    // observable even when no positive-width cell fits before a sub-unit edge.
    let after_end = after_start + after_len;
    let mut before = String::new();
    let mut before_width = 0.0;
    let mut after = String::new();
    let mut after_width = 0.0;
    let mut current_col = 0.0;
    let mut pending_ansi_before = String::new();
    let mut after_started = false;
    let mut style_tracker = AnsiCodeTracker::default();
    let mut index = 0;

    let done = |current_col: f64| {
        if after_len <= 0.0 {
            current_col >= before_end
        } else {
            current_col >= after_end
        }
    };

    'outer: while index < line.len() {
        if let Some(length) = extract_ansi_code_len(&line, index) {
            let code = &line[index..index + length];
            style_tracker.process(code);
            if current_col < before_end {
                pending_ansi_before.push_str(code);
            } else if current_col >= after_start && current_col < after_end && after_started {
                after.push_str(code);
            }
            index += length;
            continue;
        }

        let mut text_end = index;
        while text_end < line.len() && extract_ansi_code_len(&line, text_end).is_none() {
            text_end += 1;
        }
        while index < text_end {
            let (segment, width) = composite_grapheme_at(&line, index, text_end, &token_prefix);
            if current_col < before_end && current_col + width <= before_end {
                if !pending_ansi_before.is_empty() {
                    before.push_str(&pending_ansi_before);
                    pending_ansi_before.clear();
                }
                before.push_str(segment);
                before_width += width;
            } else if current_col >= after_start && current_col < after_end {
                let fits = current_col + width <= after_end;
                if fits {
                    if !after_started {
                        after.push_str(&style_tracker.get_active_codes());
                        after_started = true;
                    }
                    after.push_str(segment);
                    after_width += width;
                }
            }
            current_col += width;
            index += segment.len();
            if done(current_col) {
                break 'outer;
            }
        }
        index = text_end;
        if done(current_col) {
            break;
        }
    }

    NativeCompositeSegments {
        before,
        before_width,
        after,
        after_width,
    }
}

#[napi(js_name = "nativeSliceComposite")]
pub fn native_slice_composite(line: String, length: f64, token_prefix: String) -> String {
    if length <= 0.0 {
        return String::new();
    }

    let mut result = String::new();
    let mut current_col = 0.0;
    let mut index = 0;
    'outer: while index < line.len() {
        if let Some(code_length) = extract_ansi_code_len(&line, index) {
            if current_col >= 0.0 && current_col < length {
                result.push_str(&line[index..index + code_length]);
            }
            index += code_length;
            continue;
        }

        let mut text_end = index;
        while text_end < line.len() && extract_ansi_code_len(&line, text_end).is_none() {
            text_end += 1;
        }
        while index < text_end {
            let (segment, width) = composite_grapheme_at(&line, index, text_end, &token_prefix);
            let in_range = current_col >= 0.0 && current_col < length;
            let fits = current_col + width <= length;
            if in_range && fits {
                result.push_str(segment);
            }
            current_col += width;
            index += segment.len();
            if current_col >= length {
                break 'outer;
            }
        }
        index = text_end;
        if current_col >= length {
            break;
        }
    }
    result
}

#[napi(js_name = "nativeRenderLatex")]
pub fn native_render_latex(
    source: Utf16String,
    options: Option<NativeRenderLatexOptions>,
) -> Option<Utf16String> {
    let source = source.to_vec();
    let display = options.and_then(|options| options.display).unwrap_or(false);
    pie_core::latex::render_latex_utf16(&source, RenderLatexOptions { display })
        .map(Utf16String::from)
}

#[napi(js_name = "nativeParseOsc11BackgroundColor")]
pub fn native_parse_osc11_background_color(data: String) -> Option<NativeRgbColor> {
    pie_core::terminal_colors::parse_osc11_background_color(&data).map(|color| NativeRgbColor {
        r: color.r,
        g: color.g,
        b: color.b,
    })
}

#[napi(js_name = "nativeParseTerminalColorSchemeReport")]
pub fn native_parse_terminal_color_scheme_report(data: String) -> Option<String> {
    pie_core::terminal_colors::parse_terminal_color_scheme_report(&data).map(
        |scheme| match scheme {
            TerminalColorScheme::Dark => "dark".to_owned(),
            TerminalColorScheme::Light => "light".to_owned(),
        },
    )
}

#[napi(js_name = "nativeDetectCapabilities")]
pub fn native_detect_capabilities(
    environment: NativeTerminalEnvironment,
    tmux_forwards_hyperlinks: bool,
) -> NativeTerminalCapabilities {
    let environment = environment.into_terminal_environment();
    let capabilities =
        pie_term::capabilities::detect_capabilities(&environment, || tmux_forwards_hyperlinks);
    NativeTerminalCapabilities {
        images: capabilities.images.map_or(Either::B(Null), |protocol| {
            Either::A(match protocol {
                pie_core::terminal_image::ImageProtocol::Kitty => "kitty".to_owned(),
                pie_core::terminal_image::ImageProtocol::ITerm2 => "iterm2".to_owned(),
            })
        }),
        true_color: capabilities.true_color,
        hyperlinks: capabilities.hyperlinks,
    }
}

#[napi(js_name = "nativeImageIdFromRandom")]
pub fn native_image_id_from_random(random_unit: f64) -> u32 {
    pie_core::terminal_image::image_id_from_random(random_unit)
}

#[napi(js_name = "nativeCalculateImageRows")]
pub fn native_calculate_image_rows(
    image_dimensions: NativeImageDimensions,
    target_width_cells: f64,
    cell_dimensions: Option<NativeCellDimensions>,
) -> f64 {
    pie_core::terminal_image::calculate_image_rows(
        image_dimensions.into(),
        target_width_cells,
        cell_dimensions.map(Into::into).unwrap_or_default(),
    ) as f64
}

#[napi(js_name = "nativeEncodeKitty")]
pub fn native_encode_kitty(
    base64_data: String,
    options: Option<NativeKittyEncodeOptions>,
) -> String {
    let options = options.unwrap_or_default();
    pie_core::terminal_image::encode_kitty(
        &base64_data,
        &KittyEncodeOptions {
            columns: options.columns.map(|value| value as usize),
            rows: options.rows.map(|value| value as usize),
            image_id: options.image_id,
            move_cursor: options.move_cursor,
        },
    )
}

/// Canonical JavaScript's Kitty encoder chunks by UTF-16 code units, including
/// the possibility of splitting an astral pair. This adapter-only ABI keeps the
/// lower UTF-8 Rust codec intact while preserving the JavaScript boundary.
#[napi(js_name = "nativeEncodeKittyUtf16")]
pub fn native_encode_kitty_utf16(
    base64_data: Utf16String,
    options: Option<NativeKittyEncodeOptions>,
) -> Utf16String {
    let options = options.unwrap_or_default();
    let mut params = vec!["a=T".to_owned(), "f=100".to_owned(), "q=2".to_owned()];
    if options.move_cursor == Some(false) {
        params.push("C=1".to_owned());
    }
    if let Some(columns) = options.columns.filter(|value| *value != 0) {
        params.push(format!("c={columns}"));
    }
    if let Some(rows) = options.rows.filter(|value| *value != 0) {
        params.push(format!("r={rows}"));
    }
    if let Some(image_id) = options.image_id.filter(|value| *value != 0) {
        params.push(format!("i={image_id}"));
    }
    let params = params.join(",");
    let base64_data = base64_data.to_vec();
    let mut output = Vec::with_capacity(base64_data.len().saturating_add(96));

    if base64_data.len() <= KITTY_UTF16_CHUNK_SIZE {
        push_utf16(&mut output, &format!("\x1b_G{params};"));
        output.extend_from_slice(&base64_data);
        push_utf16(&mut output, "\x1b\\");
        return Utf16String::from(output);
    }

    for (index, chunk) in base64_data.chunks(KITTY_UTF16_CHUNK_SIZE).enumerate() {
        let is_first = index == 0;
        let is_last = (index + 1) * KITTY_UTF16_CHUNK_SIZE >= base64_data.len();
        if is_first {
            push_utf16(&mut output, &format!("\x1b_G{params},m=1;"));
        } else if is_last {
            push_utf16(&mut output, "\x1b_Gm=0;");
        } else {
            push_utf16(&mut output, "\x1b_Gm=1;");
        }
        output.extend_from_slice(chunk);
        push_utf16(&mut output, "\x1b\\");
    }
    Utf16String::from(output)
}

#[napi(js_name = "nativeEncodeITerm2")]
pub fn native_encode_iterm2(
    base64_data: String,
    options: Option<NativeITerm2EncodeOptions>,
) -> String {
    let options = options.unwrap_or_default();
    pie_core::terminal_image::encode_iterm2(
        &base64_data,
        &ITerm2EncodeOptions {
            width: options.width.map(ITerm2Dimension::Text),
            height: options.height.map(ITerm2Dimension::Text),
            name: options.name,
            preserve_aspect_ratio: options.preserve_aspect_ratio,
            inline: options.inline,
        },
    )
}

/// Adapter-only iTerm2 encoder with a JavaScript-computed decoded byte length
/// and a raw UTF-16 payload. The private legacy entry point above deliberately
/// remains available to mutation tests for the lower Rust approximation.
#[napi(js_name = "nativeEncodeITerm2Utf16")]
pub fn native_encode_iterm2_utf16(
    base64_data: Utf16String,
    decoded_size: u32,
    options: Option<NativeITerm2EncodeOptions>,
) -> Utf16String {
    let options = options.unwrap_or_default();
    let mut params = vec![
        format!("inline={}", usize::from(options.inline != Some(false))),
        format!("size={decoded_size}"),
    ];
    if let Some(width) = options.width {
        params.push(format!("width={width}"));
    }
    if let Some(height) = options.height {
        params.push(format!("height={height}"));
    }
    if let Some(name) = options.name.as_deref().filter(|name| !name.is_empty()) {
        params.push(format!("name={}", base64_encode(name.as_bytes())));
    }
    if options.preserve_aspect_ratio == Some(false) {
        params.push("preserveAspectRatio=0".to_owned());
    }

    let base64_data = base64_data.to_vec();
    let mut output = Vec::with_capacity(base64_data.len().saturating_add(96));
    push_utf16(
        &mut output,
        &format!("\x1b]1337;File={}:", params.join(";")),
    );
    output.extend_from_slice(&base64_data);
    push_utf16(&mut output, "\x07");
    Utf16String::from(output)
}

fn base64_encode(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut output = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let first = chunk[0];
        let second = chunk.get(1).copied().unwrap_or(0);
        let third = chunk.get(2).copied().unwrap_or(0);
        output.push(ALPHABET[(first >> 2) as usize] as char);
        output.push(ALPHABET[(((first & 0x03) << 4) | (second >> 4)) as usize] as char);
        output.push(if chunk.len() > 1 {
            ALPHABET[(((second & 0x0f) << 2) | (third >> 6)) as usize] as char
        } else {
            '='
        });
        output.push(if chunk.len() > 2 {
            ALPHABET[(third & 0x3f) as usize] as char
        } else {
            '='
        });
    }
    output
}

#[napi(js_name = "nativeDeleteKittyImage")]
pub fn native_delete_kitty_image(image_id: u32) -> String {
    pie_core::terminal_image::delete_kitty_image(image_id)
}

#[napi(js_name = "nativeDeleteAllKittyImages")]
pub fn native_delete_all_kitty_images() -> String {
    pie_core::terminal_image::delete_all_kitty_images().to_owned()
}

#[napi(js_name = "nativeGetPngDimensions")]
pub fn native_get_png_dimensions(base64_data: String) -> Option<NativeImageDimensions> {
    pie_core::terminal_image::get_png_dimensions(&base64_data).map(Into::into)
}

#[napi(js_name = "nativeGetJpegDimensions")]
pub fn native_get_jpeg_dimensions(base64_data: String) -> Option<NativeImageDimensions> {
    pie_core::terminal_image::get_jpeg_dimensions(&base64_data).map(Into::into)
}

#[napi(js_name = "nativeGetGifDimensions")]
pub fn native_get_gif_dimensions(base64_data: String) -> Option<NativeImageDimensions> {
    pie_core::terminal_image::get_gif_dimensions(&base64_data).map(Into::into)
}

#[napi(js_name = "nativeGetWebpDimensions")]
pub fn native_get_webp_dimensions(base64_data: String) -> Option<NativeImageDimensions> {
    pie_core::terminal_image::get_webp_dimensions(&base64_data).map(Into::into)
}

#[napi(js_name = "nativeGetImageDimensions")]
pub fn native_get_image_dimensions(
    base64_data: String,
    mime_type: String,
) -> Option<NativeImageDimensions> {
    pie_core::terminal_image::get_image_dimensions(&base64_data, &mime_type).map(Into::into)
}

#[napi(js_name = "nativeHyperlink")]
pub fn native_hyperlink(text: String, url: String) -> String {
    pie_core::terminal_image::hyperlink(&text, &url)
}

#[napi(js_name = "nativeSetKittyProtocolActive")]
pub fn native_set_kitty_protocol_active(active: bool) {
    pie_core::keys::set_kitty_protocol_active(active);
}

#[napi(js_name = "nativeIsKittyProtocolActive")]
pub fn native_is_kitty_protocol_active() -> bool {
    pie_core::keys::is_kitty_protocol_active()
}

#[napi(js_name = "nativeIsKeyRelease")]
pub fn native_is_key_release(data: String) -> bool {
    pie_core::keys::is_key_release(&data)
}

#[napi(js_name = "nativeIsKeyRepeat")]
pub fn native_is_key_repeat(data: String) -> bool {
    pie_core::keys::is_key_repeat(&data)
}

#[napi(js_name = "nativeMatchesKey")]
pub fn native_matches_key(data: String, key_id: String) -> bool {
    pie_core::keys::matches_key(&data, &key_id)
}

#[napi(js_name = "nativeParseKey")]
pub fn native_parse_key(data: String) -> Option<String> {
    pie_core::keys::parse_key(&data)
}

#[napi(js_name = "nativeDecodeKittyPrintable")]
pub fn native_decode_kitty_printable(data: String) -> Option<String> {
    pie_core::keys::decode_kitty_printable(&data)
}

#[napi(js_name = "nativeVisibleWidth")]
pub fn native_visible_width(value: String) -> f64 {
    pie_core::text::visible_width(&value) as f64
}

#[napi(js_name = "nativeStripTerminalSequences")]
pub fn native_strip_terminal_sequences(value: String) -> String {
    pie_core::text::strip_terminal_sequences(&value)
}

#[napi(js_name = "nativeGetOsc8LinkAtColumn")]
pub fn native_get_osc8_link_at_column(line: String, column: u32) -> Option<String> {
    pie_core::wrap::get_osc8_link_at_column(&line, column as usize)
}

#[napi(js_name = "nativeSliceByColumn")]
pub fn native_slice_by_column(line: String, start_col: u32, length: u32, strict: bool) -> String {
    pie_core::wrap::slice_by_column(&line, start_col as usize, length as usize, strict)
}

#[napi(js_name = "nativeTruncateToWidth")]
pub fn native_truncate_to_width(
    text: String,
    max_width: u32,
    ellipsis: String,
    pad: bool,
) -> String {
    pie_core::wrap::truncate_to_width(&text, max_width as usize, &ellipsis, pad)
}

#[napi(js_name = "nativeWrapTextWithAnsi")]
pub fn native_wrap_text_with_ansi(text: String, width: u32) -> Vec<String> {
    pie_core::wrap::wrap_text_with_ansi(&text, width as usize)
}
