/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeAltScreenPlanner {
  constructor()
  reset(): void
  get fullRedraws(): number
  render(screen: Array<string>, columns: number, rows: number): string
}

export declare class NativeEditorState {
  constructor(paddingX: number, autocompleteMaxVisible?: number | undefined | null)
  get focused(): boolean
  set focused(focused: boolean)
  get disableSubmit(): boolean
  set disableSubmit(disable: boolean)
  getPaddingX(): number
  setPaddingX(padding: number): void
  getAutocompleteMaxVisible(): number
  setAutocompleteMaxVisible(maxVisible: number): void
  addToHistory(text: string): void
  getText(): string
  getExpandedText(): string
  getLines(): Array<string>
  getCursor(): NativeEditorCursor
  setText(text: string): NativeEditorEvents
  insertTextAtCursor(text: string): NativeEditorEvents
  handleInput(data: string): NativeEditorEvents
  isShowingAutocomplete(): boolean
  invalidate(): void
  render(width: number): Array<string>
}

export declare class NativeInputState {
  constructor()
  get focused(): boolean
  set focused(focused: boolean)
  getValue(): string
  setValue(value: string): void
  handleInput(data: string): NativeInputEvents
  invalidate(): void
  render(width: number): Array<string>
}

export declare class NativeLoaderState {
  constructor(message: string, frames?: Array<string> | undefined | null, intervalMs?: number | undefined | null)
  get intervalMs(): number
  get running(): boolean
  setMessage(message: string): void
  setIndicator(frames?: Array<string> | undefined | null, intervalMs?: number | undefined | null): void
  advanceFrame(): void
  start(): void
  stop(): void
  invalidate(): void
  render(width: number): Array<string>
}

export declare class NativeMainScreenPlanner {
  constructor()
  render(lines: Array<string>, columns: number, rows: number, force: boolean, clearOnShrink: boolean, showHardwareCursor: boolean): Array<NativeTerminalAction>
  reset(): void
  setStopped(stopped: boolean): void
  get fullRedraws(): number
  capture(): NativeMainScreenRenderState
  restore(state: NativeMainScreenRenderState): void
}

export declare class NativeMarkdownState {
  constructor(text: string, paddingX: number, paddingY: number, preserveOrderedListMarkers?: boolean | undefined | null, preserveBackslashEscapes?: boolean | undefined | null, renderLatex?: boolean | undefined | null)
  setText(text: string): void
  invalidate(): void
  render(width: number): Array<string>
}

export declare class NativeSpacerState {
  constructor()
  setLines(lines: number): void
  render(): Array<string>
}

export declare class NativeStdinBufferState {
  constructor(timeoutMs: number)
  process(data: string): Array<NativeStdinEvent>
  flush(): Array<string>
  clear(): void
  getBuffer(): string
}

export declare class NativeTextState {
  constructor(text: string, paddingX: number, paddingY: number)
  setText(text: string): void
  invalidate(): void
  render(width: number): Array<string>
}

export declare class NativeTruncatedTextState {
  constructor(text: string, paddingX: number, paddingY: number)
  invalidate(): void
  render(width: number): Array<string>
}

export declare function nativeAllocateStackSizes(entries: Array<NativeStackEntry>, intrinsicSizes: Array<number>, availableSize: number | undefined | null, gap: number): Array<number>

export declare function nativeCalculateImageRows(imageDimensions: NativeImageDimensions, targetWidthCells: number, cellDimensions?: NativeCellDimensions | undefined | null): number

export interface NativeCellDimensions {
  widthPx: number
  heightPx: number
}

export interface NativeCompositeSegments {
  before: string
  beforeWidth: number
  after: string
  afterWidth: number
}

export declare function nativeCompositeVisibleWidth(line: string, tokenPrefix: string): number

export declare function nativeCursorMarker(): string

export declare function nativeDecodeKittyPrintable(data: string): string | null

export declare function nativeDeleteAllKittyImages(): string

export declare function nativeDeleteKittyImage(imageId: number): string

export declare function nativeDetectCapabilities(environment: NativeTerminalEnvironment, tmuxForwardsHyperlinks: boolean): NativeTerminalCapabilities

export interface NativeEditorCursor {
  line: number
  col: number
}

export interface NativeEditorEvents {
  submit?: string
  change?: string
}

export declare function nativeEncodeITerm2(base64Data: string, options?: NativeITerm2EncodeOptions | undefined | null): string

/**
 * Adapter-only iTerm2 encoder with a JavaScript-computed decoded byte length
 * and a raw UTF-16 payload. The private legacy entry point above deliberately
 * remains available to mutation tests for the lower Rust approximation.
 */
export declare function nativeEncodeITerm2Utf16(base64Data: string, decodedSize: number, options?: NativeITerm2EncodeOptions | undefined | null): string

export declare function nativeEncodeKitty(base64Data: string, options?: NativeKittyEncodeOptions | undefined | null): string

/**
 * Canonical JavaScript's Kitty encoder chunks by UTF-16 code units, including
 * the possibility of splitting an astral pair. This adapter-only ABI keeps the
 * lower UTF-8 Rust codec intact while preserving the JavaScript boundary.
 */
export declare function nativeEncodeKittyUtf16(base64Data: string, options?: NativeKittyEncodeOptions | undefined | null): string

export declare function nativeExtractCompositeSegments(line: string, beforeEnd: number, afterStart: number, afterLen: number, tokenPrefix: string): NativeCompositeSegments

export declare function nativeFuzzyMatchLowerUtf16(queryLower: string, textLower: string): NativeFuzzyResult

export interface NativeFuzzyResult {
  matches: boolean
  score: number
}

export declare function nativeGetGifDimensions(base64Data: string): NativeImageDimensions | null

export declare function nativeGetImageDimensions(base64Data: string, mimeType: string): NativeImageDimensions | null

export declare function nativeGetJpegDimensions(base64Data: string): NativeImageDimensions | null

export declare function nativeGetOsc8LinkAtColumn(line: string, column: number): string | null

export declare function nativeGetPngDimensions(base64Data: string): NativeImageDimensions | null

export declare function nativeGetTuiKeybindingDefinitions(): Array<NativeKeybindingDefinition>

export declare function nativeGetWebpDimensions(base64Data: string): NativeImageDimensions | null

export declare function nativeHyperlink(text: string, url: string): string

export interface NativeImageDimensions {
  widthPx: number
  heightPx: number
}

export declare function nativeImageIdFromRandom(randomUnit: number): number

export interface NativeInputEvents {
  submit?: string
  escape: boolean
}

export declare function nativeIsKeyRelease(data: string): boolean

export declare function nativeIsKeyRepeat(data: string): boolean

export declare function nativeIsKittyProtocolActive(): boolean

export interface NativeITerm2EncodeOptions {
  width?: string
  height?: string
  name?: string
  preserveAspectRatio?: boolean
  inline?: boolean
}

export interface NativeKeybindingDefinition {
  id: string
  defaultKeys: string | Array<string>
  description: string
}

export interface NativeKittyEncodeOptions {
  columns?: number
  rows?: number
  imageId?: number
  moveCursor?: boolean
}

export interface NativeMainScreenRenderState {
  previousLines: Array<string>
  previousWidth: number
  previousHeight: number
  cursorRow: number
  hardwareCursorRow: number
  maxLinesRendered: number
  previousViewportTop: number
}

export declare function nativeMatchesKey(data: string, keyId: string): boolean

export declare function nativeParseKey(data: string): string | null

export declare function nativeParseOsc11BackgroundColor(data: string): NativeRgbColor | null

export declare function nativeParseTerminalColorSchemeReport(data: string): string | null

export declare function nativeRenderLatex(source: string, options?: NativeRenderLatexOptions | undefined | null): string | null

export interface NativeRenderLatexOptions {
  display?: boolean
}

export interface NativeRgbColor {
  r: number
  g: number
  b: number
}

export declare function nativeSetKittyProtocolActive(active: boolean): void

export declare function nativeSliceByColumn(line: string, startCol: number, length: number, strict: boolean): string

export declare function nativeSliceComposite(line: string, length: number, tokenPrefix: string): string

export interface NativeStackEntry {
  basis?: number
  grow?: number
  shrink?: number
  minSize?: number
  maxSize?: number
}

export interface NativeStdinEvent {
  kind: string
  value: string
}

export declare function nativeStripTerminalSequences(value: string): string

export interface NativeTerminalAction {
  kind: string
  data?: string
}

export interface NativeTerminalCapabilities {
  images: string | null
  trueColor: boolean
  hyperlinks: boolean
}

export interface NativeTerminalEnvironment {
  termProgram?: string
  terminalEmulator?: string
  term?: string
  colorTerm?: string
  tmux?: string
  kittyWindowId?: string
  ghosttyResourcesDir?: string
  weztermPane?: string
  warpSessionId?: string
  warpTerminalSessionUuid?: string
  itermSessionId?: string
  wtSession?: string
}

export declare function nativeTruncateToWidth(text: string, maxWidth: number, ellipsis: string, pad: boolean): string

export declare function nativeVisibleWidth(value: string): number

export declare function nativeWrapTextWithAnsi(text: string, width: number): Array<string>
